# Generated by Django 5.2 on 2025-09-09 20:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_request', '0002_customuser_email'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='accessrequest',
            name='access_levels',
        ),
        migrations.RemoveField(
            model_name='accessrequest',
            name='hod_comment',
        ),
        migrations.RemoveField(
            model_name='accessrequest',
            name='hod_decision_date',
        ),
        migrations.RemoveField(
            model_name='accessrequest',
            name='hod_status',
        ),
        migrations.RemoveField(
            model_name='accessrequest',
            name='systems',
        ),
        migrations.CreateModel(
            name='RequestedSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system', models.CharField(choices=[('1', 'Active Directory'), ('2', 'CRM'), ('3', 'EDMS'), ('4', 'Email'), ('5', 'Help Desk'), ('6', 'HRMIS'), ('7', 'IDEA'), ('8', 'IFMIS'), ('9', 'Knowledge Base'), ('10', 'Services'), ('11', 'Teachers Online'), ('12', 'TeamMate'), ('13', 'TPAD'), ('14', 'TPAY'), ('15', 'Pydio')], max_length=20)),
                ('level_of_access', models.CharField(blank=True, max_length=50, null=True)),
                ('hod_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('ict_status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('hod_comment', models.TextField(blank=True, null=True)),
                ('ict_comment', models.TextField(blank=True, null=True)),
                ('access_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='requested_systems', to='access_request.accessrequest')),
            ],
        ),
    ]
