# Generated by Django 5.2 on 2025-10-04 11:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_request', '0003_remove_accessrequest_access_levels_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='hod',
            field=models.ForeignKey(blank=True, limit_choices_to={'userrole__role': 'hod'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_members', to=settings.AUTH_USER_MODEL),
        ),
    ]
