# Generated by Django 5.2 on 2025-10-04 12:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_request', '0004_customuser_hod'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrole',
            name='hod',
            field=models.ForeignKey(blank=True, limit_choices_to={'userrole__role': 'hod'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_under_hod', to=settings.AUTH_USER_MODEL),
        ),
    ]
