# Generated by Django 5.2 on 2025-10-04 12:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_request', '0005_userrole_hod'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='hod',
        ),
        migrations.AlterField(
            model_name='userrole',
            name='hod',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_members_under_me', to=settings.AUTH_USER_MODEL),
        ),
    ]
