# Generated by Django 5.2 on 2025-10-04 13:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_request', '0006_remove_customuser_hod_alter_userrole_hod'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='directorate',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='access_request.directorate'),
        ),
    ]
