# Generated by Django 5.2 on 2025-10-09 08:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_request', '0007_customuser_directorate'),
    ]

    operations = [
        migrations.AddField(
            model_name='requestedsystem',
            name='sysadmin_comment',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requestedsystem',
            name='sysadmin_decision_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='requestedsystem',
            name='sysadmin_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10),
        ),
        migrations.AddField(
            model_name='requestedsystem',
            name='system_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_systems', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='role',
            field=models.CharField(choices=[('hod', 'HOD'), ('ict', 'ICT'), ('staff', 'Staff'), ('sys_admin', 'System Administrator'), ('super_admin', 'Overall Administrator')], default='staff', max_length=20),
        ),
        migrations.CreateModel(
            name='SystemAdminAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system', models.CharField(choices=[('1', 'Active Directory'), ('2', 'CRM'), ('3', 'EDMS'), ('4', 'Email'), ('5', 'Help Desk'), ('6', 'HRMIS'), ('7', 'IDEA'), ('8', 'IFMIS'), ('9', 'Knowledge Base'), ('10', 'Services'), ('11', 'Teachers Online'), ('12', 'TeamMate'), ('13', 'TPAD'), ('14', 'TPAY'), ('15', 'Pydio')], max_length=20, unique=True)),
                ('admin_email', models.EmailField(blank=True, help_text='Optional override email for notifications', max_length=254, null=True)),
                ('admin_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='system_admin_roles', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
