# Generated by Django 5.2 on 2025-10-09 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_request', '0008_requestedsystem_sysadmin_comment_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='requestedsystem',
            name='ict_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('sent_admin', 'Sent to System Admin')], default='pending', max_length=10),
        ),
    ]
