# Generated by Django 5.2 on 2025-10-10 13:57

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_request', '0009_alter_requestedsystem_ict_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemAdmin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('system', models.CharField(choices=[('1', 'Active Directory'), ('2', 'CRM'), ('3', 'EDMS'), ('4', 'Email'), ('5', 'Help Desk'), ('6', 'HRMIS'), ('7', 'IDEA'), ('8', 'IFMIS'), ('9', 'Knowledge Base'), ('10', 'Services'), ('11', 'Teachers Online'), ('12', 'TeamMate'), ('13', 'TPAD'), ('14', 'TPAY'), ('15', 'Pydio')], max_length=50, unique=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
