# Generated by Django 5.2.7 on 2025-11-05 09:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("access_request", "0010_systemadmin"),
    ]

    operations = [
        migrations.AlterField(
            model_name="systemadmin",
            name="system",
            field=models.CharField(
                choices=[
                    ("1", "Active Directory"),
                    ("2", "CRM"),
                    ("3", "EDMS"),
                    ("4", "Email"),
                    ("5", "Help Desk"),
                    ("6", "HRMIS"),
                    ("7", "IDEA"),
                    ("8", "IFMIS"),
                    ("9", "Knowledge Base"),
                    ("10", "Services"),
                    ("11", "Teachers Online"),
                    ("12", "TeamMate"),
                    ("13", "TPAD"),
                    ("14", "TPAY"),
                    ("15", "Pydio"),
                ],
                max_length=20,
                unique=True,
            ),
        ),
        migrations.CreateModel(
            name="HodAssignment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "hod_email",
                    models.EmailField(
                        blank=True,
                        help_text="Optional override email for HOD notifications",
                        max_length=254,
                        null=True,
                    ),
                ),
                (
                    "directorate",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="hod_assignment",
                        to="access_request.directorate",
                    ),
                ),
                (
                    "hod_user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="hod_roles",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
