# Generated by Django 5.2.7 on 2025-11-12 09:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("access_request", "0011_alter_systemadmin_system_hodassignment"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("staff", "Staff"),
                            ("hod", "Head of Directorate"),
                            ("ict", "ICT Officer"),
                            ("sys_admin", "System Administrator"),
                            ("super_admin", "Overall System Admin"),
                        ],
                        default="staff",
                        max_length=20,
                    ),
                ),
                (
                    "system_assigned",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("1", "Active Directory"),
                            ("2", "CRM"),
                            ("3", "EDMS"),
                            ("4", "Email"),
                            ("5", "Help Desk"),
                            ("6", "HRMIS"),
                            ("7", "IDEA"),
                            ("8", "IFMIS"),
                            ("9", "Knowledge Base"),
                            ("10", "Services"),
                            ("11", "Teachers Online"),
                            ("12", "TeamMate"),
                            ("13", "TPAD"),
                            ("14", "TPAY"),
                            ("15", "Pydio"),
                        ],
                        max_length=20,
                        null=True,
                    ),
                ),
                (
                    "directorate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="users",
                        to="access_request.directorate",
                    ),
                ),
                (
                    "hod",
                    models.ForeignKey(
                        blank=True,
                        limit_choices_to={"profile__role": "hod"},
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="staff_members",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
    ]
