# Generated by Django 5.2.7 on 2025-11-12 11:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("access_request", "0012_userprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="requestedsystem",
            name="directorate",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="access_request.directorate",
            ),
        ),
    ]
