# Generated by Django 5.2.7 on 2025-11-17 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("access_request", "0013_requestedsystem_directorate"),
    ]

    operations = [
        migrations.AddField(
            model_name="requestedsystem",
            name="hod_decision_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="requestedsystem",
            name="ict_decision_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
