# Generated by Django 5.2.7 on 2025-11-18 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("access_request", "0014_requestedsystem_hod_decision_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SystemAnalytics",
            fields=[],
            options={
                "verbose_name": "📊 System Dashboard",
                "verbose_name_plural": "📊 System Dashboard",
                "proxy": True,
                "indexes": [],
                "constraints": [],
            },
            bases=("access_request.accessrequest",),
        ),
        migrations.AlterField(
            model_name="accessrequest",
            name="request_type",
            field=models.CharField(
                choices=[
                    ("new", "New User"),
                    ("modify", "Change/Modify"),
                    ("deactivate", "Deactivate"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="accessrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending_hod", "Pending HOD"),
                    ("rejected_hod", "Rejected HOD"),
                    ("pending_ict", "Pending ICT"),
                    ("rejected_ict", "Rejected ICT"),
                    ("approved", "Approved"),
                    ("revoked", "Access Revoked"),
                ],
                default="pending_hod",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="hodassignment",
            name="hod_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="requestedsystem",
            name="ict_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("sent_admin", "Sent to Admin"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="requestedsystem",
            name="sysadmin_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("revoked", "Revoked"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
        migrations.AlterField(
            model_name="systemadminassignment",
            name="admin_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("staff", "Staff"),
                    ("hod", "HOD"),
                    ("ict", "ICT"),
                    ("sys_admin", "SysAdmin"),
                    ("super_admin", "SuperAdmin"),
                ],
                default="staff",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="userrole",
            name="role",
            field=models.CharField(
                choices=[
                    ("hod", "HOD"),
                    ("ict", "ICT"),
                    ("staff", "Staff"),
                    ("sys_admin", "System Admin"),
                    ("super_admin", "Overall Admin"),
                ],
                default="staff",
                max_length=20,
            ),
        ),
    ]
