# Generated by Django 5.2.7 on 2025-11-19 08:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("access_request", "0016_accesslog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userprofile",
            name="hod",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="staff_members",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="userprofile",
            name="role",
            field=models.CharField(
                choices=[
                    ("hod", "HOD"),
                    ("ict", "ICT"),
                    ("staff", "Staff"),
                    ("sys_admin", "System Admin"),
                    ("super_admin", "Overall Admin"),
                ],
                default="staff",
                max_length=20,
            ),
        ),
    ]
