# Generated by Django 5.2.7 on 2025-11-19 09:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("access_request", "0017_alter_userprofile_hod_alter_userprofile_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customuser",
            name="email",
            field=models.EmailField(
                blank=True,
                error_messages={"unique": "Email address already exists."},
                max_length=254,
                null=True,
                unique=True,
            ),
        ),
        migrations.AlterField(
            model_name="customuser",
            name="tsc_no",
            field=models.CharField(
                error_messages={"unique": "TSC Number already exists."},
                max_length=20,
                unique=True,
            ),
        ),
    ]
