# Generated by Django 5.2.7 on 2025-11-20 12:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("access_request", "0018_alter_customuser_email_alter_customuser_tsc_no"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="systemadmin",
            name="user",
        ),
        migrations.RemoveField(
            model_name="systemadminassignment",
            name="admin_user",
        ),
        migrations.AlterModelOptions(
            name="userrole",
            options={"verbose_name": "User Role", "verbose_name_plural": "User Roles"},
        ),
        migrations.AlterField(
            model_name="userrole",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="role_assignment",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.DeleteModel(
            name="HodAssignment",
        ),
        migrations.DeleteModel(
            name="SystemAdmin",
        ),
        migrations.DeleteModel(
            name="SystemAdminAssignment",
        ),
    ]
