# Generated by Django 5.2.7 on 2025-11-20 12:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("access_request", "0019_remove_systemadmin_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userrole",
            name="directorate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="hod_user",
                to="access_request.directorate",
            ),
        ),
        migrations.AddField(
            model_name="userrole",
            name="system_assigned",
            field=models.CharField(
                blank=True,
                choices=[
                    ("1", "Active Directory"),
                    ("2", "CRM"),
                    ("3", "EDMS"),
                    ("4", "Email"),
                    ("5", "Help Desk"),
                    ("6", "HRMIS"),
                    ("7", "IDEA"),
                    ("8", "IFMIS"),
                    ("9", "Knowledge Base"),
                    ("10", "Services"),
                    ("11", "Teachers Online"),
                    ("12", "TeamMate"),
                    ("13", "TPAD"),
                    ("14", "TPAY"),
                    ("15", "Pydio"),
                ],
                help_text="System this admin is responsible for (only for System Admin role)",
                max_length=20,
                null=True,
            ),
        ),
    ]
