# Generated by Django 5.2.7 on 2025-11-20 12:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("access_request", "0020_userrole_directorate_userrole_system_assigned"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userrole",
            name="user",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="userrole",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
