# Generated by Django 5.2.7 on 2026-01-08 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("access_request", "0022_globalsettings_auditlog_securitypolicy_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="accessrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending_hod", "Pending HOD"),
                    ("rejected_hod", "Rejected HOD"),
                    ("pending_ict", "Pending ICT"),
                    ("rejected_ict", "Rejected ICT"),
                    ("pending_sysadmin", "Pending System Admin"),
                    ("rejected_sysadmin", "Rejected System Admin"),
                    ("approved", "Approved"),
                    ("revoked", "Access Revoked"),
                ],
                default="pending_hod",
                max_length=20,
            ),
        ),
    ]
